name = "miner-design-site"
main = "./src/index.js"
compatibility_date = "2026-06-20"

[assets]
directory = "./public/"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "STREAMBOT_DB"
database_name = "miner-streambot"
database_id = "77503bf0-64f6-4683-bd37-acad4c1fc111"
